services:
  replica1:
    build: .
    container_name: replica1
    networks:
      - electrode_net
    command: /bin/bash -c "sudo ./bench/replica -c /app/config.txt -m vr -i 0"
    privileged: true

  replica2:
    build: .
    container_name: replica2
    networks:
      - electrode_net
    command: /bin/bash -c "sudo ./bench/replica -c /app/config.txt -m vr -i 1"
    privileged: true

  replica3:
    build: .
    container_name: replica3
    networks:
      - electrode_net
    command: /bin/bash -c "sudo ./bench/replica -c /app/config.txt -m vr -i 2"
    privileged: true

  client:
    build: .
    container_name: client
    networks:
      - electrode_net
    depends_on:
      - replica1
      - replica2
      - replica3
    command: /bin/bash -c "./bench/client -c /app/config.txt -m vr -n 10000"

networks:
  electrode_net:
    driver: bridge