version: '3.8'

services:
  replica1:
    build: ./
    container_name: replica1
    networks:
      - electrode_net
    command: /bin/bash -c "taskset -c 1 ./bench/replica -c config.txt -m vr -i 0"
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    privileged: true

  replica2:
    build: ./
    container_name: replica2
    networks:
      - electrode_net
    command: /bin/bash -c "taskset -c 1 ./bench/replica -c config.txt -m vr -i 1" 
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    privileged: true

  replica3:
    build: ./
    container_name: replica3
    networks:
      - electrode_net
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    command: /bin/bash -c "taskset -c 1 ./bench/replica -c config.txt -m vr -i 2" 
    privileged: true

  client:
    build: ./
    container_name: client
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    networks:
      - electrode_net
    depends_on:
      - replica1
      - replica2
      - replica3
    command: /bin/bash -c "./bench/client -c config.txt -m vr -n 10000"
    privileged: true

networks:
  electrode_net:
    driver: bridge

